version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/go:0-1.20
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity

  db:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: sekret

volumes:
  mysql-data:
